### NN Test

In [1]:
import sys
sys.path.insert(0, '/Users/Sergiomendes/Desktop/SIB/SIB/src/si')
# print(sys.path)

from neural_networks.layers import Dense, SigmoidActivation, SoftMaxActivation, ReLUActivation, LinearActivation
from neural_networks.nn import NN
from data.dataset import Dataset
import numpy as np

In [2]:
x = np.array([[0,0],
              [0,1],
              [1,0],
              [1,1]])

y = np.array([1,
              0,
              0,
              1])

dataset = Dataset(X=x, y=y, features=['x1', 'x2'], label='x1 XNOR x2')
dataset.print_dataframe()

x1  x2
1   0   0
0   0   1
0   1   0
1   1   1

In [3]:
# weights and bias for the 1st layer

# first row is the first node of the second layer
# rows are the input nodes
l1_weight_matrix = np.array([[20, -20],
                             [20, -20]])

l1_bias = np.array([[-30, 10]])

layer1 = Dense(input_size=2, output_size=2)
layer1.weights = l1_weight_matrix
layer1.bias = l1_bias

In [4]:

# weights and bias for the 2nd layer

l2_weight_matrix = np.array([[20],
                             [20]])

l2_bias = np.array([[-10]])

layer2 = Dense(input_size=2, output_size=1)
layer2.weights = l2_weight_matrix
layer2.bias = l2_bias

In [5]:
layer1_sigmoid = SigmoidActivation()
layer2_sigmoid = SigmoidActivation()

# between layers, we have the layer activation
nn_model = NN(
    layers=[layer1, layer1_sigmoid, layer2, layer2_sigmoid]
)

In [6]:
nn_model.fit(dataset=dataset)

In [7]:
nn_model.predict(dataset=dataset)

array([[9.99954561e-01],
       [4.54803785e-05],
       [4.54803785e-05],
       [9.99954561e-01]])

## Exercise 10
### Binary Classification Problem

In [8]:
# Create an adequate training dataset
x_3 = np.random.randn(100, 32)  # 100 samples with 32 features of random floats
y_3 = np.random.randint(0, 2, size=(100, 1))  # labels for the 100 samples of random binary integers

dataset_3 = Dataset(x_3, y_3)

In [9]:
layer3_1 = Dense(input_size=32, output_size=32)
layer3_2 = Dense(input_size=32, output_size=16)
layer3_3 = Dense(input_size=16, output_size=1)  #if score is <0.5 the output is 0, and if score is >0.5 the output is 1

layer3_1activation = SigmoidActivation()
layer3_2activation = SigmoidActivation()
layer3_3activation= SigmoidActivation()

# between layers, we have the layer activation
nn_model3 = NN(
    layers=[layer3_1, layer3_1activation, layer3_2, layer3_2activation, layer3_3, layer3_3activation]
)

In [10]:
nn_model3.fit(dataset=dataset_3)

In [11]:
nn_model3.predict(dataset=dataset_3)

array([[0.49105787],
       [0.49105916],
       [0.49105559],
       [0.49105961],
       [0.49105964],
       [0.49105491],
       [0.49105928],
       [0.49105806],
       [0.49105937],
       [0.49106046],
       [0.49105735],
       [0.49105608],
       [0.4910535 ],
       [0.49105476],
       [0.49105882],
       [0.49106006],
       [0.49105923],
       [0.49105874],
       [0.49106114],
       [0.49106034],
       [0.49105991],
       [0.49105591],
       [0.49105888],
       [0.49105708],
       [0.49105554],
       [0.49105753],
       [0.49105655],
       [0.49105709],
       [0.4910585 ],
       [0.49105879],
       [0.49105776],
       [0.49105991],
       [0.49105669],
       [0.49105994],
       [0.49105873],
       [0.49105835],
       [0.49105656],
       [0.49105731],
       [0.49105665],
       [0.49105659],
       [0.49105911],
       [0.49105384],
       [0.49105886],
       [0.49105722],
       [0.49105659],
       [0.49105794],
       [0.49105742],
       [0.491

### Multiclass Classification Problem

In [12]:
# Create an adequate training dataset
x_4 = np.random.randn(100, 32)  # 100 samples with 32 features of random floats
y_4 = np.random.randint(0, 3, size=(100, 1))  # labels for the 100 samples with 3 different classes

dataset_4 = Dataset(x_4, y_4)

In [13]:
layer4_1 = Dense(input_size=32, output_size=32)
layer4_2 = Dense(input_size=32, output_size=16)
layer4_3 = Dense(input_size=16, output_size=3)  # will assign each output to the corresponding class according to the score

layer4_1activation = SigmoidActivation()
layer4_2activation= SigmoidActivation()
layer4_3activation = SoftMaxActivation()  # will assign a probability to each class that summed together will add up to 1

# between layers, we have the layer activation
nn_model4 = NN(
    layers=[layer4_1, layer4_1activation, layer4_2, layer4_2activation, layer4_3, layer4_3activation]
)

In [14]:
nn_model4.fit(dataset=dataset_4)

In [ ]:
nn_model4.predict(dataset=dataset_4)

### Regression Problem

In [15]:
# Create an adequate training dataset
x_5 = np.random.randn(100, 32)  # 100 samples with 32 features of random floats
y_5 = np.random.randn(100, 1)  # labels for the 100 samples of random floats

dataset_5 = Dataset(x_5, y_5)

In [16]:
layer5_1 = Dense(input_size=32, output_size=32)
layer5_2 = Dense(input_size=32, output_size=16)
layer5_3 = Dense(input_size=16, output_size=1)  # returns a single continuous target for each sample

layer5_1activation = ReLUActivation()
layer5_2activation = ReLUActivation()
layer5_3activation = LinearActivation()  # returns a real values for our output

# between layers, we have the layer activation
nn_model5 = NN(
    layers=[layer5_1, layer5_1activation, layer5_2, layer5_2activation, layer5_3, layer5_3activation]
)

In [17]:
nn_model5.fit(dataset=dataset_5)

In [18]:
nn_model5.predict(dataset=dataset_5)

array([[ 1.02164165e-05],
       [ 7.84938221e-05],
       [ 1.23811965e-04],
       [ 6.67774194e-05],
       [-8.21508306e-06],
       [-1.53192014e-05],
       [ 4.30583702e-05],
       [ 1.97363960e-05],
       [ 1.82501060e-06],
       [ 4.04512590e-05],
       [-5.13390477e-05],
       [ 1.63591453e-05],
       [ 4.50634324e-05],
       [ 1.97118925e-05],
       [-1.03435639e-05],
       [-4.87051497e-05],
       [-2.00238379e-05],
       [-2.05531716e-05],
       [ 4.63870647e-06],
       [ 2.76320660e-05],
       [ 4.61693156e-05],
       [-1.19417719e-05],
       [ 6.04721330e-05],
       [ 6.65073335e-06],
       [ 6.20321982e-05],
       [ 3.41907823e-05],
       [-6.18030036e-07],
       [ 2.90000976e-05],
       [-1.55974606e-07],
       [ 5.06726019e-06],
       [-1.22868033e-05],
       [ 6.17204554e-05],
       [ 8.64353140e-05],
       [ 2.07909838e-05],
       [ 2.94036984e-05],
       [-1.81914093e-05],
       [ 5.37400711e-05],
       [-7.41697783e-06],
       [ 2.8